// Build-time: self-host the Arabic faces and emit a fonts.css that preserves
// Google's unicode-range subsetting, so the browser downloads only the Arabic
// subset for Arabic text. Offline-first means no font request at runtime.
import fs from 'node:fs'
import path from 'node:path'
import { ROOT, ensure, log, kb } from './_util.mjs'

const OUT = ensure(path.join(ROOT, 'public', 'fonts'))
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120 Safari/537.36'

const FACES = [
  { slug: 'amiri-quran',  css: 'https://fonts.googleapis.com/css2?family=Amiri+Quran&display=swap' },
  { slug: 'scheherazade', css: 'https://fonts.googleapis.com/css2?family=Scheherazade+New:wght@400;700&display=swap' },
  { slug: 'noto-naskh',   css: 'https://fonts.googleapis.com/css2?family=Noto+Naskh+Arabic:wght@400;700&display=swap' }
]

async function main() {
  log('Sabeel \u00b7 Fonts')
  let out = '/* Generated by scripts/fetch-fonts.mjs \u2014 do not edit by hand. */\n'
  let bytes = 0

  for (const f of FACES) {
    const css = await (await fetch(f.css, { headers: { 'User-Agent': UA } })).text()
    const blocks = css.split('@font-face').slice(1)
    let i = 0
    for (const b of blocks) {
      const url = b.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1]
      if (!url) continue
      const range = b.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
      const weight = b.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() || '400'
      const family = b.match(/font-family:\s*'([^']+)'/)?.[1] || f.slug

      const name = `${f.slug}-${++i}.woff2`
      const buf = Buffer.from(await (await fetch(url)).arrayBuffer())
      fs.writeFileSync(path.join(OUT, name), buf)
      bytes += buf.length

      out += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:swap;`
        + `src:url('/fonts/${name}') format('woff2');`
        + (range ? `unicode-range:${range};` : '')
        + '}\n'
    }
    log(`  ${f.slug.padEnd(14)} ${i} subsets`)
  }

  fs.writeFileSync(path.join(OUT, 'fonts.css'), out)
  log(`  wrote fonts.css \u00b7 ${kb(bytes)} of woff2`)
}
main().catch(e => { console.error('FAILED:', e.message); process.exit(1) })
